export const SIGN_OUT_REQUEST = 'SIGN_OUT_REQUEST';

export const SIGN_IN_REQUEST = 'SIGN_IN_REQUEST';
export const SIGN_IN_SUCCESS = 'SIGN_IN_SUCCESS';
export const SIGN_IN_FAILURE = 'SIGN_IN_FAILURE';

export const FAKE_TOKEN_EXPIRY_REQUEST = 'FAKE_TOKEN_EXPIRY_REQUEST';

export const FAKE_ERROR = 'FAKE_ERROR';

export const DO_SOMETHING_REQUEST = 'DO_SOMETHING_REQUEST';
export const DO_SOMETHING_SUCCESS = 'DO_SOMETHING_SUCCESS';
export const DO_SOMETHING_FAILURE = 'DO_SOMETHING_FAILURE';

export const DO_SOMETHING_WITH_PROMISE_REQUEST = 'DO_SOMETHING_WITH_PROMISE_REQUEST';
export const DO_SOMETHING_WITH_PROMISE_SUCCESS = 'DO_SOMETHING_WITH_PROMISE_SUCCESS';
export const DO_SOMETHING_WITH_PROMISE_FAILURE = 'DO_SOMETHING_WITH_PROMISE_FAILURE';
